language: php

php:
  - 5.6

env:
  global:
    - setup=basic
    - APP_ENV=staging
    - APP_DEBUG=true
    - DB_CONNECTION=sqlite
    - CACHE_DRIVER=file
    - SESSION_DRIVER=file
    - QUEUE_DRIVER=sync

sudo: false

install:
- php artisan serve >/dev/null 2>&1 &

before_script:
- php artisan key:generate
- php artisan config:clear
- php artisan serve >/dev/null 2>&1 &

script:
- vendor/bin/phpunit
